version: "2"

networks:
  app-tier:
    driver: bridge

services:
  etcd:
    image: "bitnami/etcd:latest"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-tier
  frontend:
    image: dievri/silverkey-web
    volumes:
      - ./configs:/etc/nginx/conf.d
      - ./build:/usr/local/openresty/nginx/html/
    ports:
      - "8080:80"
    networks:
      - app-tier
  # ui:
  #   image: buddho/etcd-browser
  #   environment:
  #     ETCD_HOST: etcd
  #     ETCD_PORT: 2379
  #   ports:
  #     - 0.0.0.0:2888:8000
